#!/usr/bin/env bash


mirror="https://mirrors.edge.kernel.org/linuxmint-packages"

latest_version_x_icons=$(curl "$mirror"/pool/main/m/mint-x-icons/ 2>/dev/null |
	grep '.deb' |
	grep '<a href="mint-x-icons' |
	cut -d'>' -f4 | cut -d'<' -f1 |
	sort | tail -n 1)

latest_version_x_icons_number=$(echo $latest_version_x_icons |
	cut -d'_' -f2 | cut -d'_' -f1)

installed_version_x_icons=$(dpkg --status mint-x-icons |
	grep -e '^Version: ' | cut -d' ' -f2)

latest_version_y_icons=$(curl "$mirror"/pool/main/m/mint-y-icons/ 2>/dev/null |
	grep '.deb' | grep '<a href="mint-y-icons' |
	cut -d'>' -f4 | cut -d'<' -f1 |
	sort | tail -n 1)

latest_version_y_icons_number=$(echo $latest_version_y_icons |
	cut -d'_' -f2 | cut -d'_' -f1)

latest_version_mint_themes=$(curl "$mirror"/pool/main/m/mint-themes/ 2>/dev/null |
	grep '.deb' | grep '<a href="mint-theme' |
	cut -d'>' -f4 | cut -d'<' -f1 |
	sort | tail -n 1)

latest_version_mint_themes=$(echo $latest_version_mint_themes |
	cut -d'_' -f2 | cut -d'_' -f1)

is_installed() {
	if dpkg --status $1 2>/dev/null
	then
		echo "true"
	else
		echo "false"
	fi
}

if [[ is_installed mint-x-icons == "false" ]]
then	
	wget "$mirror"/pool/main/m/mint-x-icons/$latest_version_x_icons \
		-O /tmp/$latest_version_x_icons
fi

if [[ is_installed mint-y-icons == "false" ]]
then
wget "$mirror"/pool/main/m/mint-y-icons/$latest_version_y_icons \
		-O /tmp/$latest_version_y_icons

if [[ is_installed mint-themes == "false" ]]
then
	wget "$mirror"/pool/main/m/mint-themes/$latest_version_mint_themes \
		-O /tmp/$latest_version_mint_themes
fi

echo "Installing $latest_version_x_icons..."
sudo dpkg -i /tmp/$latest_version_x_icons && echo "Done!" || echo "Error!"

echo "Installing $latest_version_y_icons..."
sudo dpkg -i /tmp/$latest_version_y_icons && echo "Done!" || echo "Error!"

echo "Installing $latest_version_mint_themes..."
sudo dpkg -i /tmp/$latest_version_mint_themes && echo "Done!" || echo "Error!"

sudo rm -rf /tmp/$latest_version_x_icons
rm -rf /tmp/$latest_version_y_icons
rm -rf /tmp/$latest_version_mint_themes
